@startuml
'https://plantuml.com/class-diagram

class BegudaMonster {
    -- Atributs --
    - nom: String
    - sabor: String
    - cafeina: Float
    - color: String
    - volum: Int
    -- Mètodes --
    + constructor(String, String, Float, String, Int)
    + getCafeina(): Float
}

class Participant {
    -- Atributs --
    - nom: String
    - dataNaixement: Date
    - totalCafeina: Float
    - begudes: List<BegudaMonster>
    -- Mètodes --
    + constructor(String, LocalDate, Float, List<BegudaMonster>)
    + registrarConsum(BegudaMonster)
    + consultarCafeina(): Float
    + calcularEdat(): Int
    - recalcularTotalCafeina(): Float
}
Participant "1" o-down- "M" BegudaMonster: Consumeix

@enduml