@startuml
'https://plantuml.com/class-diagram

enum TipusPokemons {
    foc
    aigua
    planta
    electric
}

enum RetornComparacio {
    empat
    guanya1
    guanya2
}

class CartaPokemon {
    -- Atributs --
    - nom: String
    - tipus: TipusPokemons
    - puntsAtac: Int
    - puntsDefensa: Int
    -- Mètodes --
    + constructor(String, TipusPokemons, Int, Int)
    + getNom(): String
    + poderTotal(): Int
    + compararPoder(poderTotal(), CartaPokemon): RetornComparacio
}

class JugadorPokemon {
    -- Atributs --
    - nom: String
    - cartes: List<CartaPokemon>
    -- Mètodes --
    + constructor(String, List<CartaPokemon>)
}

CartaPokemon o-down- JugadorPokemon
CartaPokemon "N" *-left- "1" TipusPokemons: és
CartaPokemon *-right- RetornComparacio

@enduml